image: python:3.9

pipelines:
  branches:
    main:
      - step:
          name: Build and Upload to PyPI
          caches:
            - pip
          script:
            - pip install --upgrade pip setuptools wheel twine build
            - python -m build
            - twine upload dist/*.whl -p $PYPI_PASSWORD
          services:
            - docker